version: '3'
services:
  php-fpm:
    build: './docker/php-fpm'
    volumes: 
      - .:/var/www/html
    depends_on:
      - mysql
  nginx:
    build: './docker/nginx'
    volumes: 
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
    depends_on:
      - php-fpm
  mysql:
    build: './docker/mysql'
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    ports:
      - "33061:3306"

volumes:
  db-store: